### PR TITLE
Rewrite terminal core in Go

### PR DESCRIPTION
**Pull request by mipearson**
WFM!

Letting Ruby handle Emoji for now. This imparts an approximately 2x performance penalty on large sets .. but it's still miles ahead of the Ruby impl. Original acceptance tests have been ported from Ruby to Go, and I've added a couple of additional ones for correctness of multibyte handling.

Benches:
```
     npm.sh.raw ruby        0.8 (±0.0%) i/s -          4 in   5.183151s # original ruby
          npm.sh.raw        4.5 (±0.0%) i/s -         23 in   5.071450s # go via gem
    npm.sh.raw gocmd        9.0 (±0.0%) i/s -         46 in   5.092831s # go command run directly (no emoji)
     npm.sh.raw http       10.3 (±9.7%) i/s -         52 in   5.072454s # go via http (no emoji)
```

### CODE REVIEW

**Comment by toolmantim** [comment]
Ok, so Terminal 2.0.0 has been released, which no longer does the encoding or emoji munging. We're good to switch to using this super-powered Golang version. Now… do we just use this repo or start a fresh one for the golang version?

**Comment by mipearson** [comment]
Can you tell me why you dropped the encoding stuff and/or how you dropped it? Worried that I'll need to change my impl.

**Comment by toolmantim** [comment]
I've just put the onus onto the invoker to ensure they're passing in UTF-8. If you have your locale set incorrectly, then it'll bork. I don't think you need to do anything on the go side.

**Comment by toolmantim** [comment]
For context, if you pass in a wrongly-encoded UTF-8 string to the Ruby gem it throws an error in the regex gear. Not something you need to do I presume.

**Comment by mipearson** [comment]
New PR: https://github.com/buildkite/terminal/pull/14

**Pull request closed without merging**
