### PR TITLE
Webserver hosted image support

### PR DESCRIPTION
**Pull request by mipearson**

### CODE REVIEW

**Comment by toolmantim** [comment]
IT WORKS!

Now, I wonder about the embedding-foreign-content thing. Can we have a way of allowing only local and https image paths? I wonder if there's any attack vectors here…

**Comment by toolmantim** [comment]
Ok, so after doing a bunch of integration work I reckon:

* Change to `url=` instead of `path=` as the syntax. This will make it feel much different to the `1337` escape code (which is a good thing… `path` could almost be a feature of the iTerm/1337 escape code syntax). Then we just tell people to put `artifact://` for artifacts, or just paste the URL in. Also then we're not telling people to put "urls" in the "path" if you know what I mean.
* Forget about the `--assets` argument. With the `artifact://` URL scheme we don't need it, we'll do all the re-writing/g-subbing etc on the Ruby side (which we already need to do).
* It'd be nice to give people a way to set a meaningful alt tag?

**Comment by mipearson** [comment]
:+1:, including the alt tag. Give that a whirl.

**Comment by toolmantim** [comment]
Wee! I'll integrate this tonight.

"Reconstituted semicolons" would also make for a cool t-shirt :+1:

**Comment by toolmantim** [comment]
:+1: works a treat! Let's ship it.

**Comment by toolmantim** [comment]
Hold onto your pants, this is going live.

**Pull request merged**
